// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pricer.proto

package api_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PriceRequest struct {
	Pricingdate          float64  `protobuf:"fixed64,1,opt,name=pricingdate,proto3" json:"pricingdate,omitempty"`
	Strike               float64  `protobuf:"fixed64,2,opt,name=strike,proto3" json:"strike,omitempty"`
	Expiry               float64  `protobuf:"fixed64,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	PutCall              string   `protobuf:"bytes,4,opt,name=put_call,json=putCall,proto3" json:"put_call,omitempty"`
	Spot                 float64  `protobuf:"fixed64,5,opt,name=spot,proto3" json:"spot,omitempty"`
	Vol                  float64  `protobuf:"fixed64,6,opt,name=vol,proto3" json:"vol,omitempty"`
	Rate                 float64  `protobuf:"fixed64,7,opt,name=rate,proto3" json:"rate,omitempty"`
	ClientId             string   `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceRequest) Reset()         { *m = PriceRequest{} }
func (m *PriceRequest) String() string { return proto.CompactTextString(m) }
func (*PriceRequest) ProtoMessage()    {}
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec020e99f204f1f, []int{0}
}

func (m *PriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceRequest.Unmarshal(m, b)
}
func (m *PriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceRequest.Marshal(b, m, deterministic)
}
func (m *PriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceRequest.Merge(m, src)
}
func (m *PriceRequest) XXX_Size() int {
	return xxx_messageInfo_PriceRequest.Size(m)
}
func (m *PriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PriceRequest proto.InternalMessageInfo

func (m *PriceRequest) GetPricingdate() float64 {
	if m != nil {
		return m.Pricingdate
	}
	return 0
}

func (m *PriceRequest) GetStrike() float64 {
	if m != nil {
		return m.Strike
	}
	return 0
}

func (m *PriceRequest) GetExpiry() float64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *PriceRequest) GetPutCall() string {
	if m != nil {
		return m.PutCall
	}
	return ""
}

func (m *PriceRequest) GetSpot() float64 {
	if m != nil {
		return m.Spot
	}
	return 0
}

func (m *PriceRequest) GetVol() float64 {
	if m != nil {
		return m.Vol
	}
	return 0
}

func (m *PriceRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *PriceRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type PriceResponse struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	ValueType            string   `protobuf:"bytes,2,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ClientId             string   `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceResponse) Reset()         { *m = PriceResponse{} }
func (m *PriceResponse) String() string { return proto.CompactTextString(m) }
func (*PriceResponse) ProtoMessage()    {}
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec020e99f204f1f, []int{1}
}

func (m *PriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceResponse.Unmarshal(m, b)
}
func (m *PriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceResponse.Marshal(b, m, deterministic)
}
func (m *PriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceResponse.Merge(m, src)
}
func (m *PriceResponse) XXX_Size() int {
	return xxx_messageInfo_PriceResponse.Size(m)
}
func (m *PriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceResponse proto.InternalMessageInfo

func (m *PriceResponse) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PriceResponse) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

func (m *PriceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *PriceResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func init() {
	proto.RegisterType((*PriceRequest)(nil), "gobs.PriceRequest")
	proto.RegisterType((*PriceResponse)(nil), "gobs.PriceResponse")
}

func init() { proto.RegisterFile("pricer.proto", fileDescriptor_fec020e99f204f1f) }

var fileDescriptor_fec020e99f204f1f = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x4e, 0xe3, 0x30,
	0x14, 0x85, 0xe5, 0x36, 0x4d, 0x1b, 0xb7, 0x23, 0xcd, 0x78, 0x46, 0xa3, 0x50, 0x40, 0xaa, 0xb2,
	0xaa, 0x40, 0x24, 0x08, 0x76, 0xb0, 0x83, 0x05, 0x62, 0x87, 0x02, 0x0b, 0xc4, 0x26, 0x72, 0x52,
	0x2b, 0x35, 0xb8, 0xb9, 0xc6, 0x76, 0x0a, 0xdd, 0xf2, 0x0a, 0xbc, 0x19, 0xbc, 0x02, 0x0f, 0x82,
	0x6c, 0x17, 0xa9, 0xdd, 0xdd, 0xf3, 0xe5, 0xfe, 0xf8, 0xe4, 0xe0, 0x91, 0x54, 0xbc, 0x62, 0x2a,
	0x95, 0x0a, 0x0c, 0x90, 0xa0, 0x86, 0x52, 0x8f, 0xf7, 0x6a, 0x80, 0x5a, 0xb0, 0x8c, 0x4a, 0x9e,
	0xd1, 0xa6, 0x01, 0x43, 0x0d, 0x87, 0x46, 0xfb, 0x9e, 0xe4, 0x03, 0xe1, 0xd1, 0x8d, 0x1d, 0xca,
	0xd9, 0x73, 0xcb, 0xb4, 0x21, 0x13, 0x3c, 0xb4, 0x4b, 0x78, 0x53, 0xcf, 0xa8, 0x61, 0x31, 0x9a,
	0xa0, 0x29, 0xca, 0x37, 0x11, 0xf9, 0x8f, 0x43, 0x6d, 0x14, 0x7f, 0x62, 0x71, 0xc7, 0x7d, 0x5c,
	0x2b, 0xcb, 0xd9, 0xab, 0xe4, 0x6a, 0x15, 0x77, 0x3d, 0xf7, 0x8a, 0xec, 0xe0, 0x81, 0x6c, 0x4d,
	0x51, 0x51, 0x21, 0xe2, 0x60, 0x82, 0xa6, 0x51, 0xde, 0x97, 0xad, 0xb9, 0xa4, 0x42, 0x10, 0x82,
	0x03, 0x2d, 0xc1, 0xc4, 0x3d, 0x37, 0xe0, 0x6a, 0xf2, 0x1b, 0x77, 0x97, 0x20, 0xe2, 0xd0, 0x21,
	0x5b, 0xda, 0x2e, 0x65, 0xdf, 0xd2, 0xf7, 0x5d, 0xb6, 0x26, 0xbb, 0x38, 0xaa, 0x04, 0x67, 0x8d,
	0x29, 0xf8, 0x2c, 0x1e, 0xb8, 0xad, 0x03, 0x0f, 0xae, 0x67, 0xc9, 0x0b, 0xfe, 0xb5, 0xf6, 0xa4,
	0x25, 0x34, 0x9a, 0x91, 0x7f, 0xb8, 0xb7, 0xa4, 0xa2, 0xfd, 0xb1, 0xe3, 0x05, 0xd9, 0xc7, 0xd8,
	0x15, 0x85, 0x59, 0x49, 0x6f, 0x26, 0xca, 0x23, 0x47, 0xee, 0x56, 0xd2, 0x0d, 0x31, 0xa5, 0x40,
	0x39, 0x3b, 0x51, 0xee, 0xc5, 0xf6, 0xe1, 0x60, 0xfb, 0xf0, 0xc9, 0xfd, 0xfa, 0xb0, 0xba, 0x65,
	0x6a, 0xc9, 0x2b, 0x46, 0xae, 0x70, 0xcf, 0x01, 0x42, 0x52, 0x1b, 0x46, 0xba, 0xf9, 0xab, 0xc7,
	0x7f, 0xb7, 0x98, 0x7f, 0x6a, 0xf2, 0xe7, 0xed, 0xf3, 0xeb, 0xbd, 0x33, 0x4c, 0xc2, 0xcc, 0x65,
	0x79, 0x86, 0x0e, 0xa6, 0xe8, 0x18, 0x5d, 0x1c, 0x3d, 0x1c, 0xd6, 0xdc, 0xcc, 0xdb, 0x32, 0xad,
	0x60, 0x91, 0x09, 0x36, 0xa7, 0x8f, 0x74, 0x91, 0xd5, 0x00, 0xd2, 0xa6, 0x99, 0xd9, 0x45, 0x36,
	0xe1, 0x73, 0x2a, 0x79, 0x21, 0xcb, 0x32, 0x74, 0xe9, 0x9e, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x18, 0xf1, 0xd4, 0xe3, 0x11, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PricerServiceClient is the client API for PricerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PricerServiceClient interface {
	Price(ctx context.Context, opts ...grpc.CallOption) (PricerService_PriceClient, error)
}

type pricerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricerServiceClient(cc grpc.ClientConnInterface) PricerServiceClient {
	return &pricerServiceClient{cc}
}

func (c *pricerServiceClient) Price(ctx context.Context, opts ...grpc.CallOption) (PricerService_PriceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PricerService_serviceDesc.Streams[0], "/gobs.PricerService/Price", opts...)
	if err != nil {
		return nil, err
	}
	x := &pricerServicePriceClient{stream}
	return x, nil
}

type PricerService_PriceClient interface {
	Send(*PriceRequest) error
	Recv() (*PriceResponse, error)
	grpc.ClientStream
}

type pricerServicePriceClient struct {
	grpc.ClientStream
}

func (x *pricerServicePriceClient) Send(m *PriceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pricerServicePriceClient) Recv() (*PriceResponse, error) {
	m := new(PriceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PricerServiceServer is the server API for PricerService service.
type PricerServiceServer interface {
	Price(PricerService_PriceServer) error
}

// UnimplementedPricerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPricerServiceServer struct {
}

func (*UnimplementedPricerServiceServer) Price(srv PricerService_PriceServer) error {
	return status.Errorf(codes.Unimplemented, "method Price not implemented")
}

func RegisterPricerServiceServer(s *grpc.Server, srv PricerServiceServer) {
	s.RegisterService(&_PricerService_serviceDesc, srv)
}

func _PricerService_Price_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PricerServiceServer).Price(&pricerServicePriceServer{stream})
}

type PricerService_PriceServer interface {
	Send(*PriceResponse) error
	Recv() (*PriceRequest, error)
	grpc.ServerStream
}

type pricerServicePriceServer struct {
	grpc.ServerStream
}

func (x *pricerServicePriceServer) Send(m *PriceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pricerServicePriceServer) Recv() (*PriceRequest, error) {
	m := new(PriceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PricerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gobs.PricerService",
	HandlerType: (*PricerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Price",
			Handler:       _PricerService_Price_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pricer.proto",
}
